---
title: "Graphing Presidents' names"
output: html_notebook
---

```{r}
library(tidyverse)
library(dplyr)
```

Read in csv files for wiki data and external data. Goal of this notebook is to merge the two tables and graph the data.

```{r}
wiki_original <- read_csv('wiki_decade_table.csv')

ext_original <- read_csv('perf_presidents.csv')
```

Calculated percentage of males named president name in the decade specified and made a new column.

```{r}
wiki_original <- wiki_original %>%
  mutate(percentage = President_names/n)
```

We want to merge the tables and to have only the columns we are interested in.

```{r}
wiki_imp <- wiki_original %>%
  select(correct_decade, percentage)

ext_imp <- ext_original %>%
  select(name, percentage)


wikipedia123 <- (wiki_imp[,2])
ext_imp[, 'Wikipedia_Percentage'] <- wikipedia123

```

```{r}
all_data_tall <- ext_imp %>%
  pivot_longer(-name, names_to = 'Data', values_to = 'Percent')

all_data_tall <- all_data_tall %>%
  mutate(Data = ifelse(Data == 'percentage', 'External', 'Wikipedia'))

all_data_tall <- all_data_tall %>%
  mutate(Percent = Percent*100)
    
```


```{r}
ggplot(data = all_data_tall, aes(x = name, fill = Data)) +
  geom_col(aes(y = Percent), position = 'dodge') +
  xlab('Names (Wikipedia data vs. External data)') +
  ylab('Percent of male popualtion with specified name') +
  ggtitle('Popularity of Presidents\' names in the following decade of their election') +
  scale_color_brewer(name = 'Data', palette = 'Accent')

ggsave('President_names_popularity.pdf')
```

```{r}
library(xtable)
xtable(all_data_tall)
```

