---
title: "President Names"
output: html_notebook
---

We want to look at the percent of boys named the same first name as the president of the decade they were born into.

```{r}
library(tidyverse)
```

Three variables are made of each csv file for the three names.

```{r}
Grover <- read_csv('Grover.csv')

Theodore <- read_csv('Theodore.csv')

Richard <- read_csv('Richard.csv')

Ronald <- read_csv('Ronald.csv')
```

Proceed to sum the annual percentages to find one value for the decade to define the popularity of a name.

```{r}
Grover_Decade <- Grover %>%
  summarise(Decade_popularity = mean(Popularity))

Theodore_Decade <- Theodore %>%
  summarise(Decade_popularity = mean(Popularity))

Richard_Decade <- Richard %>%
  summarise(Decade_popularity = mean(Popularity))

Ronald_Decade <- Ronald %>%
  summarise(Decade_popularity = mean(Popularity))
```

Now that the variables have been found, a dataset can be made to plot the data.


```{r}
# reading the wikipedia csv file
wiki_names <- read_csv('presidents.csv') 
  mutate(
    birthyear = as.numeric(birthyear)
  )
```


```{r}
# Finding occasions of name = president_name
wiki_presidential_names <- wiki_names %>%
  mutate(
    presidents_full = case_when(
      str_detect(name,"Ronald") ~ "Ronald",
      str_detect(name,"Richard") ~ "Richard",
      str_detect(name,"Theodore") ~ "Theodore",
      str_detect(name,"Grover") ~ "Grover",
      TRUE ~ "Other")
    )  %>%
  mutate(
    correct_decade = case_when(
      birthyear >= 1980 & birthyear <= 1991 ~ "Ronald Decade",
      birthyear >= 1968 & birthyear <= 1979 ~ "Richard Decade",
      birthyear >= 1900 & birthyear <= 1911 ~ "Theodore Decade",
      birthyear >= 1884 & birthyear <= 1895 ~ "Grover Decade",
      TRUE ~ "Other")
    )

# Adding selection for decade
#wiki_presidential_name_data <- wiki_presidential_names %>%
 # mutate(presidents_full = case_when(
  #  int_detect(birthyear, decade_grover))
  #)
  
# new variable
# group by president_full & decade
# summarize()

  # 
  # mutate(
  #   Grover1 = (str_detect(name, "Grover") & birthyear < 1894),
  #   Grover_yes = ifelse(Grover1, 'GROVER', 'NOT GROVER')
  # ) %>%
  # mutate(
  #   Theodore1 = (str_detect(name, "Theodore") & birthyear < 1911 & birthyear > 1900 ),
  #   Theodore_yes = ifelse(Theodore1, 'THEODORE', 'NOT THEODORE')
  # ) %>%
  # mutate(
  #   Richard1 = (str_detect(name, "Richard") & birthyear < 1979 & birthyear > 1968 ),
  #   Richard_yes = ifelse(Richard1, 'RICHARD', 'NOT RICHARD')
  # ) %>%
  # mutate(
  #   Ronald1 = (str_detect(name, "Ronald") & birthyear < 1991 & birthyear > 1980),
  #   Ronald_yes = ifelse(Ronald1, 'RONALD', 'NOT RONALD')
  # ) %>%
  #   
  # 
  # mutate(
  #   presidents_full = case_when(
  #     Ronald1 ~ "Ronald",
  #     Richard1 ~ "Richard",
  #     Theodore1 ~ "Theodore",
  #     Grover1 ~ "Grover",
  #     TRUE ~ ""
  #     
  #   )
  # )
#  mutate(
#    presidents_full = '',
 #   presidents_full = ifelse(Ronald1, "Ronald", presidents_full)
  #)
#    presidentsfull = if(Ronald1 == TRUE 'RONALD') if (Grover1 == TRUE 'GROVER') if (Richard1 == TRUE 'RICHARD') if (Theodore1 == TRUE 'THEODORE') else ('none')






```
```{r}
wiki_decade_table <- wiki_presidential_names %>%
  group_by(correct_decade) %>%
  count()


wiki_decade_table2 <- wiki_presidential_names %>%
  group_by(presidents_full) %>%
  count()


decade123 <- (wiki_decade_table2[,2])
wiki_decade_table[, 'President names'] <- decade123

wiki_decade_table <- filter(wiki_decade_table[0-2,])


  
```
